name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build
      run: |
        go build -v
        strip rdig
      env:
        CGO_ENABLED: "0"
    - name: Save binaries
      uses: actions/upload-artifact@v3
      with:
        path: rdig
        name: rdig
